# MD5: f32e0c1e177ce84b1e7630e469c467ed
set(CFG_ENABLE_BUILD_VARS YES) 

set(CFG_FEATURE_UPGRADE_TL YES) 

set(CFG_PRODUCT_NAME "hi6932_udp") 

set(CFG_PRODUCT_CFG_CHIP_SOLUTION_NAME "Balong") 

set(CFG_BUILD_TYPE RELEASE) 

set(CFG_PRODUCT_VERSION V700R220C30B010) 

set(CFG_PRODUCT_VERSION_STR "V700R220C30B010") 

set(CFG_PRODUCT_FULL_VERSION_STR "Balong V700R220C30B010") 

set(CFG_PRODUCT_FILE_VERSION_STR "2.1.6.8") 

set(CFG_PRODUCT_DLOAD_SOFTWARE_VER		 "21.120.00.00.010") 

set(CFG_PLATFORM hi6932) 

set(CFG_PLATFORM_HISI_BALONG hi6932) 

set(CFG_ARCH_TYPE	 3339) 

set(CFG_OS_LINUX_PRODUCT_NAME hi6932_udp_defconfig) 

set(CFG_TARGET_BALONG_PRODUCT hi6932_udp) 

set(CFG_USE_USBLOADER_MERGE 			 YES) 

set(CFG_BSP_ENBALE_PACK_IMAGE			 YES) 

set(CFG_BSP_USB_BURN					 YES) 

set(CFG_CONFIG_COMPRESS_CCORE_IMAGE YES) 

set(CFG_BUILD_PTABLE YES) 

set(CFG_CONFIG_VERSION_STUB YES) 

set(CFG_HW_VERSION_STUB 0x72000000) 

set(CFG_BSP_CONFIG_EDA NO) 

set(CFG_BSP_CONFIG_EMU NO) 

set(CFG_BSP_CONFIG_NOT_DDR_BYPASSPLL NO) 

set(CFG_BSP_HAS_SEC_FEATURE NO) 

set(CFG_CONFIG_SMART_SYSTEM_MODEM NO) 

set(CFG_CONFIG_FASTBOOT_DEBUG NO) 

set(CFG_FEATURE_MULTIMODE_GUL YES) 

set(CFG_CONFIG_NVIM YES) 

set(CFG_FEATURE_NV_FLASH_ON YES) 

set(CFG_FEATURE_NV_EMMC_ON NO) 

set(CFG_FEATURE_NV_LFILE_ON NO) 

set(CFG_FEATURE_NV_RFILE_ON NO) 

set(CFG_FEATURE_TLPHY_MAILBOX YES) 

set(CFG_CONFIG_MAILBOX_TYPE YES) 

set(CFG_CONFIG_HIFI_MAILBOX YES) 

set(CFG_ENABLE_BUILD_OM YES) 

set(CFG_FEATURE_OM_PHONE NO) 

set(CFG_ENABLE_BUILD_SYSVIEW YES) 

set(CFG_ENABLE_BUILD_CPUVIEW YES) 

set(CFG_ENABLE_BUILD_MEMVIEW YES) 

set(CFG_ENABLE_BUILD_AMON YES) 

set(CFG_ENABLE_BUILD_UTRACE NO) 

set(CFG_FEATURE_SIM_NOTIFY NO) 

set(CFG_CONFIG_SC NO) 

set(CFG_CONFIG_GPIO_SYNOPSYS NO) 

set(CFG_CONFIG_PCIE_CFG YES) 

set(CFG_CONFIG_COUL NO) 

set(CFG_CONFIG_SFLASH NO) 

set(CFG_CONFIG_ABB YES) 

set(CFG_CONFIG_DSP YES) 

set(CFG_CONFIG_HIFI YES) 

set(CFG_CONFIG_HKADC NO) 

set(CFG_CONFIG_ONOFF YES) 

set(CFG_CONFIG_BBP NO) 

set(CFG_CONFIG_MIPI NO) 

set(CFG_CONFIG_LEDS_CCORE NO) 

set(CFG_CONFIG_FB_SPI_BALONG NO) 

set(CFG_CONFIG_FB_EMI_BALONG NO) 

set(CFG_CONFIG_FB_1_4_5_INCH_BALONG NO) 

set(CFG_CONFIG_FB_2_4_INCH_BALONG NO) 

set(CFG_CONFIG_SLIC m) 

set(CFG_CONFIG_TEMPERATURE_PROTECT NO) 

set(CFG_CONFIG_ANTEN NO) 

set(CFG_CONFIG_EFUSE YES) 

set(CFG_CONFIG_BURN_EFUSE_NANDC NO) 

set(CFG_CONFIG_DDM YES) 

set(CFG_CONFIG_TSENSOR YES) 

set(CFG_CONFIG_DESIGNWARE_I2C NO) 

set(CFG_FEATURE_E5_ONOFF NO) 

set(CFG_CONFIG_FASTBOOT_UART_NUM 1) 

set(CFG_CONFIG_MODULE_VIC NO) 

set(CFG_CONFIG_AT_UART NO) 

set(CFG_CONFIG_CSHELL YES) 

set(CFG_CONFIG_ICC YES) 

set(CFG_CONFIG_OF YES) 

set(CFG_CONFIG_CPUFREQ YES) 

set(CFG_CONFIG_CCORE_REGULATOR YES) 

set(CFG_CONFIG_CCORE_WDT YES) 

set(CFG_CONFIG_ACORE_WDT YES) 

set(CFG_ENABLE_BUILD_SOCP YES) 

set(CFG_CONFIG_BALONG_CCLK YES) 

set(CFG_CONFIG_CCORE_CPU_IDLE YES) 

set(CFG_CONFIG_CCORE_PM YES) 

set(CFG_CONFIG_MODULE_IPC YES) 

set(CFG_CONFIG_MODULE_TIMER YES) 

set(CFG_CONFIG_MODULE_SYNC YES) 

set(CFG_CONFIG_HAS_CCORE_WAKELOCK YES) 

set(CFG_CONFIG_CCORE_BALONG_PM NO) 

set(CFG_CONFIG_BALONG_EDMA YES) 

set(CFG_CONFIG_BALONG_EDMA_TEST YES) 

set(CFG_CONFIG_HWADP YES) 

set(CFG_CONFIG_BALONG_HPM_TEMP NO) 

set(CFG_CONFIG_MEM YES) 

set(CFG_CONFIG_TCXO_BALONG NO) 

set(CFG_CONFIG_BALONG_DPM NO) 

set(CFG_CONFIG_USE_TIMER_STAMP NO) 

set(CFG_CONFIG_MODULE_BUSSTRESS NO) 

set(CFG_CONFIG_IPF YES) 

set(CFG_CONFIG_PSAM YES) 

set(CFG_CONFIG_CIPHER YES) 

set(CFG_CONFIG_IPF_VESION 2) 

set(CFG_CONFIG_IPF_ADQ_LEN 3) 

set(CFG_CONFIG_IPF_BACKUP_ON_LPM3 YES) 

set(CFG_CONFIG_USB_DWC3_VBUS_DISCONNECT YES) 

set(CFG_USB3_SYNOPSYS_PHY NO) 

set(CFG_CONFIG_USB_FORCE_HIGHSPEED NO) 

set(CFG_ENABLE_TEST_CODE NO) 

set(CFG_PRODUCT_CFG_PTABLE_VER_NAME "V7R500_UDP") 

set(CFG_PRODUCT_CFG_PTABLE_VER_ID			 "ptable 1.00") 

set(CFG_PRODUCT_CFG_FLASH_M3BOOT_LEN     	 0x40000) 

set(CFG_PRODUCT_CFG_FLASH_FASTBOOT_LEN 0xC0000) 

set(CFG_PRODUCT_CFG_FLASH_NV_LTE_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_NV_IMG_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_NV_DLD_LEN      	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_NV_FACTORY_LEN   	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_OEMINFO_LEN 0x200000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_USERDATA_LEN 0x600000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_ONLINE_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_BOOTIMG_LEN	 0x600000) 

set(CFG_PRODUCT_CFG_FLASH_BOOTIMGBAK_LEN	 0) 

set(CFG_PRODUCT_CFG_FLASH_LOGO_LEN 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_DSP_LEN  		 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_HIFI_LEN  	 0x300000) 

set(CFG_PRODUCT_CFG_FLASH_MISC_LEN 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_CCORE_LEN  	 0x1000000) 

set(CFG_PRODUCT_CFG_FLASH_M3IMAGE_LEN 	 0x100000) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE1_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE2_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_RESERVE3_LEN 0) 

set(CFG_PRODUCT_CFG_FLASH_OM_LEN 0xC00000) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_APP_LEN 0x0) 

set(CFG_PRODUCT_CFG_FLASH_YAFFS_WEBUI_LEN 	 0x0) 

set(CFG_PRODUCT_CFG_FLASH_SYSIMG_LEN 0x2800000) 

set(CFG_PRODUCT_CFG_FLASH_DTIMG_LEN 0x00800000) 

set(CFG_PRODUCT_CFG_FLASH_ISO_LEN 0x1000000) 

set(CFG_PRODUCT_CFG_FLASH_CACHE_LEN   	 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_RECOVERY_LEN 0x400000) 

set(CFG_PRODUCT_CFG_FLASH_MULTI_CARRIER_LEN 0x00000) 

set(CFG_FLASH_PTABLE_OFFSET						 0x1F800) 

set(CFG_MCORE_TEXT_START_ADDR 0xA0400000) 

set(CFG_FASTBOOT_DDR_ENTRY 0xAFD00000) 

set(CFG_PRODUCT_CFG_KERNEL_ENTRY 		 0xA7E08000) 

set(CFG_PRODUCT_KERNEL_PARAMS_PHYS		 0xA7E00100) 

set(CFG_ONCHIP_FASTBOOT_ADDR 0xAF900000) 

set(CFG_RTX_KERNEL_ENTRY 0x10000000) 

set(CFG_HI_SRAM_MEM_ADDR 0x80800000) 

set(CFG_HI_SRAM_SIZE 0x2000) 

set(CFG_DRV_SRAM_ADDR               		 (HI_SRAM_MEM_ADDR)) 

set(CFG_DRV_SRAM_SIZE						 0x2000) 

set(CFG_DDR_MEM_ADDR 0xA0000000) 

set(CFG_DDR_MEM_SIZE       		 0x10000000) 

set(CFG_DDR_APP_ACP_ADDR (DDR_MEM_ADDR)) 

set(CFG_DDR_APP_ACP_SIZE 0x000000) 

set(CFG_DDR_GU_ADDR ((DDR_APP_ACP_ADDR) + (DDR_APP_ACP_SIZE))) 

set(CFG_DDR_GU_SIZE 0x00C0000) 

set(CFG_DDR_UPA_ADDR DDR_GU_ADDR) 

set(CFG_DDR_UPA_SIZE 0x00024000) 

set(CFG_DDR_CQI_ADDR ((DDR_UPA_ADDR) + (DDR_UPA_SIZE))) 

set(CFG_DDR_CQI_SIZE 0x00003400) 

set(CFG_DDR_APT_ADDR ((DDR_CQI_ADDR) + (DDR_CQI_SIZE))) 

set(CFG_DDR_APT_SIZE 0x00008400) 

set(CFG_DDR_ET_ADDR ((DDR_APT_ADDR) + (DDR_APT_SIZE))) 

set(CFG_DDR_ET_SIZE 0x00004800) 

set(CFG_DDR_NV_ADDR ((DDR_ET_ADDR) + (DDR_ET_SIZE))) 

set(CFG_DDR_NV_SIZE 0x00000000) 

set(CFG_DDR_ZSP_UP_ADDR ((DDR_NV_ADDR) + (DDR_NV_SIZE))) 

set(CFG_DDR_ZSP_UP_SIZE 0x00008000) 

set(CFG_DDR_ECS_TEE_ADDR ((DDR_ZSP_UP_ADDR) + (DDR_ZSP_UP_SIZE))) 

set(CFG_DDR_ECS_TEE_SIZE 0x00001800) 

set(CFG_DDR_RESERVE_ADDR ((DDR_ECS_TEE_ADDR) + (DDR_ECS_TEE_SIZE))) 

set(CFG_DDR_RESERVE_SIZE 0x00082800) 

set(CFG_DDR_TLPHY_IMAGE_ADDR     	 ((DDR_RESERVE_ADDR) + (DDR_RESERVE_SIZE))) 

set(CFG_DDR_TLPHY_IMAGE_SIZE     	 0x340000) 

set(CFG_DDR_MCORE_ADDR (( DDR_TLPHY_IMAGE_ADDR ) + (DDR_TLPHY_IMAGE_SIZE))) 

set(CFG_DDR_MCORE_SIZE 0x5D00000) 

set(CFG_DDR_MCORE_DTS_ADDR ((DDR_MCORE_ADDR) + (DDR_MCORE_SIZE))) 

set(CFG_DDR_MCORE_DTS_SIZE 0x0100000) 

set(CFG_DDR_SHARED_MEM_ADDR ((DDR_MNTN_ADDR) + (DDR_MNTN_SIZE))) 

set(CFG_DDR_SHARED_MEM_SIZE 0x400000) 

set(CFG_DDR_HIFI_MBX_ADDR			 (DDR_SHARED_MEM_ADDR)) 

set(CFG_DDR_HIFI_MBX_SIZE			 (0X9800)) 

set(CFG_DDR_MNTN_ADDR ((DDR_SECURE_OS_ADDR) + (DDR_SECURE_OS_SIZE))) 

set(CFG_DDR_MNTN_SIZE 0x100000) 

set(CFG_DDR_LPHY_SDR_ADDR ((DDR_MCORE_DTS_ADDR) + (DDR_MCORE_DTS_SIZE))) 

set(CFG_DDR_LPHY_SDR_SIZE 0x280000) 

set(CFG_DDR_LCS_ADDR ((DDR_LPHY_SDR_ADDR) + (DDR_LPHY_SDR_SIZE))) 

set(CFG_DDR_LCS_SIZE 0x280000) 

set(CFG_DDR_HIFI_ADDR ((DDR_SHARED_MEM_ADDR) + (DDR_SHARED_MEM_SIZE))) 

set(CFG_DDR_HIFI_SIZE 0x200000) 

set(CFG_DDR_ACORE_ADDR ((DDR_HIFI_ADDR) + (DDR_HIFI_SIZE))) 

set(CFG_DDR_ACORE_SIZE 0x2E00000) 

set(CFG_DDR_ACORE_DTS_ADDR ((DDR_ACORE_ADDR) + (DDR_ACORE_SIZE))) 

set(CFG_DDR_ACORE_DTS_SIZE 0x0100000) 

set(CFG_DDR_SOCP_ADDR ((DDR_ACORE_DTS_ADDR) + (DDR_ACORE_DTS_SIZE))) 

set(CFG_DDR_SOCP_SIZE 0x300000) 

set(CFG_DDR_MDM_ACP_ADDR ((DDR_SOCP_ADDR) + (DDR_SOCP_SIZE))) 

set(CFG_DDR_MDM_ACP_SIZE 0x0) 

set(CFG_NV_DDR_SIZE (0x200000)) 

