obj-$(CONFIG_HISI_COULOMETER_HI6421V500)	+= hi6421v500/
obj-$(CONFIG_HISI_COULOMETER)	            += hisi_coul_core.o hisi_coul_drv.o hisi_battery_data.o
obj-$(CONFIG_HISI_COULOMETER_TEST)        += hisi_coul_drv_test.o
