include("${CMAKE_CURRENT_LIST_DIR}/product_config_legacy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_drv.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_pam.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucas.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucnas.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_gucphy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/product_config_audio.cmake")
