# MD5: 05408bd2528d37e1f1795c3c5d3d77be
set(CFG_TENSILICA_BUILDS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RE-2014.5-linux) 

set(CFG_TENSILICA_TOOLS_HIFI $(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RE-2014.5-linux) 

set(CFG_FEATURE_HIFI FEATURE_OFF) 

set(CFG_FEATURE_HIFI_USE_ICC FEATURE_OFF) 

set(CFG_FEATURE_MBB_MODULE_AUDIO FEATURE_OFF) 

set(CFG_FEATURE_VOICE_UP FEATURE_OFF) 

