# MD5: cfa50d5ae9cbc7b5f8c1878c60aa6352
set(CFG_FEATURE_BBP_MASTER FEATURE_ON) 

set(CFG_BBP_MASTER_INT_MODE FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_EXTEND FEATURE_OFF) 

set(CFG_FEATURE_GUC_BBP_TRIG FEATURE_OFF) 

set(CFG_FEATURE_MULTI_FS_PARTITION FEATURE_OFF) 

set(CFG_FEATURE_POWER_TIMER FEATURE_OFF) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_ON) 

