#
#NoC Makefile
#

subdir-ccflags-$(CONFIG_HISI_BB)               += -Idrivers/hisi/mntn/blackbox/
subdir-ccflags-$(CONFIG_HISI_NOC)              += -Idrivers/hisi/mntn/
obj-$(CONFIG_HISI_NOC) +=  hisi_noc.o hisi_err_probe.o hisi_noc_packet.o hisi_noc_bus.o hisi_noc_transcation.o hisi_noc_id_addr.o hisi_noc_dbg.o hisi_noc_dump.o

