# MD5: 8a5bab35170d667df56ce57813314a4c
CFG_FEATURE_IMS                                 := FEATURE_ON
CFG_FEATURE_LTE_R11                             := FEATURE_ON
CFG_FEATURE_LTE_MBMS                            := FEATURE_OFF
CFG_FEATURE_LTE_NAS_R11                         := FEATURE_OFF
CFG_FEATURE_LTE_CDMA_R11                        := FEATURE_OFF
CFG_FEATURE_PTM                                 := FEATURE_OFF
CFG_FEATURE_BALONG_CL                           := FEATURE_UE_MODE_CDMA
CFG_FEATURE_LTE_CAT_PART_R11                    := NO
CFG_TL_PS_MAX_TRCH_NUM_8    := YES
CFG_FEATURE_LPP                                 := FEATURE_OFF
