# MD5: 8e62ac8aec1666e2e98490f365be2b29
set(CFG_FEATURE_BBP_MASTER FEATURE_ON) 

set(CFG_BBP_MASTER_INT_MODE FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_EXTEND FEATURE_ON) 

set(CFG_FEATURE_MULTI_FS_PARTITION FEATURE_OFF) 

set(CFG_FEATURE_POWER_TIMER FEATURE_OFF) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_ON) 

set(CFG_FEATURE_GUC_BBP_TRIG FEATURE_OFF) 

