# MD5: 8a5bab35170d667df56ce57813314a4c
set(CFG_FEATURE_IMS FEATURE_ON) 

set(CFG_FEATURE_LTE_R11 FEATURE_ON) 

set(CFG_FEATURE_LTE_MBMS FEATURE_OFF) 

set(CFG_FEATURE_LTE_NAS_R11 FEATURE_OFF) 

set(CFG_FEATURE_LTE_CDMA_R11 FEATURE_OFF) 

set(CFG_FEATURE_PTM FEATURE_OFF) 

set(CFG_FEATURE_BALONG_CL FEATURE_UE_MODE_CDMA) 

set(CFG_FEATURE_LTE_CAT_PART_R11 NO) 

set(CFG_TL_PS_MAX_TRCH_NUM_8 YES) 

set(CFG_FEATURE_LPP FEATURE_OFF) 

